#!/bin/sh
#######################################################
status=`mpstat | grep all `
#sys=`mpstat | grep all | awk '{print $6}' `
#niceratio=`mpstat | grep all | awk '{print $5}' 
#waitratio=`mpstat | grep all | awk '{print $7}'
#stolen=`mpstat | grep all | awk '{print $10}'
users=`mpstat | grep all | awk '{print $4}' `
#######################################################
if [ $? = 0 ]
then 
	echo "OK - the use ratio  of CPU is : $status |sysrate=$users "
	exit 0
else 
	echo "UNKNOWN - can not get performance data you want "
	exit 3
fi
