#!/bin/sh
##################################################################
#get average speed of last 5 s

nicName=$1
alertSpeed=$2


speed=`sar 5 1 -n DEV |  grep "Average:" | grep $nicName | awk '{print $5+$6}'`
timenow=`date +%T`

cSpeed=`echo $speed |awk '{print $1*100 }'`
cAlertSpeed=`echo $alertSpeed |awk '{print $1*100 }'`


#echo $cSpeed
#echo $cAlertSpeed



if [  -n $speed ]
then

	if [ $cAlertSpeed -gt  $cSpeed  ]
		then  
			echo "OK - Time: $timenow ; nicName: $nicName ;  averageSpeed of last 5s : $speed KBps ;alertValue is $alertSpeed KBps |speed=$speed "
			exit 0
	else
			echo "Critical - Time: $timenow ; nicName: $nicName ;  averageSpeed of last 5s : $speed KBps ;alertValue is $alertSpeed KBps |speed=$speed "				
			exit 2
	fi
else 
	echo "Unkown - $timenow may be  the script is not executed "
	exit 3
fi
