#!/bin/sh
fromhost="192.168.7.225"
hostaddress="10.200.1.120"
#hostaddress="192.168.7.1"
warninvalue=5000000
criticalvalue=10000000

###############################################
status=`ping -c 10  $hostaddress |grep rtt ` 
if [ -n $status ]
then
	echo "CRITICAL -from: $fromhost dest: $hostaddress info: the dest address unreachable | timedelay= 0 "
        exit 2
else

delay=`echo $status |awk -F"/" '{print $5 }'`
timedelay=`echo $status |awk -F"/" '{print $5*10000 }'`
####################################################
echo $delay $timedelay

if [ $timedelay -lt $warninvalue ]
	then
		echo "OK - from: $fromhost dest: $hostaddress info:$status | timedelay=$delay "
		exit 0
elif [  $timedelay -ge $warninvalue ] && [  $timedelay -lt $criticalvalue ]
	then
		echo "WARNING -from: $fromhost dest: $hostaddress info:$status | timedelay=$delay "
		exit 1
elif [ $timedelay -ge $criticalvalue ]
	then 
		echo "CRITICAL -from: $fromhost dest: $hostaddress info:$status | timedelay=$delay  "
		exit 2

fi
 
fi
