/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.18 from the
 * contents of vxs.xs. Do not edit this file, edit vxs.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "vxs.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#define NEED_sv_2pv_nolen_GLOBAL
#include "ppport.h"
#include "vutil.h"

/* --------------------------------------------------
 * $Revision: 2.5 $
 * --------------------------------------------------*/

typedef     SV *version_vxs;

#line 24 "vxs.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 166 "vxs.c"

XS_EUPXS(XS_version__vxs_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_version__vxs_new)
{
    dVAR; dXSARGS;
    dXSI32;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 44 "vxs.xs"
{
    SV *vs = ST(1);
    SV *rv;
    const char * classname = "";
    PERL_UNUSED_ARG(ix);

    if (items > 3 || items == 0)
        Perl_croak(aTHX_ "Usage: version::new(class, version)");

    if ( items == 1 || ! SvOK(vs) ) { /* no param or explicit undef */
        /* create empty object */
        vs = sv_newmortal();
        sv_setpvs(vs,"undef");
    }
    else if ( items == 2 && SvOK(ST(1)) ) {
        /* getting called as object or class method */
        vs = ST(1);
    }
    else if (items == 3 ) {
        vs = sv_newmortal();
        sv_setpvf(vs,"v%s",SvPV_nolen_const(ST(2)));
    }
    classname =
	sv_isobject(ST(0)) /* get the class if called as an object method */
	    ? HvNAME_get(SvSTASH(SvRV(ST(0))))
	    : (char *)SvPV_nolen(ST(0));

    rv = NEW_VERSION(vs);
    if ( strcmp(classname,"version::vxs") != 0 ) /* inherited new() */
#if PERL_VERSION == 5
        sv_bless(rv, gv_stashpv((char *)classname, GV_ADD));
#else
        sv_bless(rv, gv_stashpv(classname, GV_ADD));
#endif

    mPUSHs(rv);
}
#line 215 "vxs.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_version__vxs_stringify); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_version__vxs_stringify)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "lobj, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	version_vxs	lobj;

        if (ISA_CLASS_OBJ(ST(0), "version")) {
	    lobj = SvRV(ST(0));
        }
        else
            Perl_croak(aTHX_ "lobj is not of type version::vxs")
;
#line 86 "vxs.xs"
{
    mPUSHs(VSTRINGIFY(lobj));
}
#line 243 "vxs.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_version__vxs_numify); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_version__vxs_numify)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "lobj, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	version_vxs	lobj;

        if (ISA_CLASS_OBJ(ST(0), "version")) {
	    lobj = SvRV(ST(0));
        }
        else
            Perl_croak(aTHX_ "lobj is not of type version::vxs")
;
#line 94 "vxs.xs"
{
    mPUSHs(VNUMIFY(lobj));
}
#line 271 "vxs.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_version__vxs_normal); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_version__vxs_normal)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "ver");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	ver = ST(0)
;
#line 102 "vxs.xs"
{
    mPUSHs(VNORMAL(ver));
}
#line 293 "vxs.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_version__vxs_VCMP); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_version__vxs_VCMP)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "lobj, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	version_vxs	lobj;

        if (ISA_CLASS_OBJ(ST(0), "version")) {
	    lobj = SvRV(ST(0));
        }
        else
            Perl_croak(aTHX_ "lobj is not of type version::vxs")
;
#line 110 "vxs.xs"
{
    SV *rs;
    SV *rvs;
    SV *robj = ST(1);
    const IV  swap = (IV)SvIV(ST(2));

    if ( ! ISA_CLASS_OBJ(robj, "version::vxs") )
    {
        robj = NEW_VERSION(SvOK(robj) ? robj : newSVpvs_flags("undef", SVs_TEMP));
        sv_2mortal(robj);
    }
    rvs = SvRV(robj);

    if ( swap )
    {
        rs = newSViv(VCMP(rvs,lobj));
    }
    else
    {
        rs = newSViv(VCMP(lobj,rvs));
    }

    mPUSHs(rs);
}
#line 342 "vxs.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_version__vxs_boolean); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_version__vxs_boolean)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "lobj, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	version_vxs	lobj;

        if (ISA_CLASS_OBJ(ST(0), "version")) {
	    lobj = SvRV(ST(0));
        }
        else
            Perl_croak(aTHX_ "lobj is not of type version::vxs")
;
#line 139 "vxs.xs"
{
    SV * const rs =
    	newSViv( VCMP(lobj,
		      sv_2mortal(NEW_VERSION(
		      		 sv_2mortal(newSVpvs("0"))
				))
		     )
	       );
    mPUSHs(rs);
}
#line 377 "vxs.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_version__vxs_noop); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_version__vxs_noop)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "lobj, ...");
    {
	version_vxs	lobj;

        if (ISA_CLASS_OBJ(ST(0), "version")) {
	    lobj = SvRV(ST(0));
        }
        else
            Perl_croak(aTHX_ "lobj is not of type version::vxs")
;
#line 154 "vxs.xs"
{
    Perl_croak(aTHX_ "operation not supported with version object");
}
#line 403 "vxs.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_version__vxs_is_alpha); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_version__vxs_is_alpha)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "lobj");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	version_vxs	lobj;

        if (ISA_CLASS_OBJ(ST(0), "version")) {
	    lobj = SvRV(ST(0));
        }
        else
            Perl_croak(aTHX_ "lobj is not of type version::vxs")
;
#line 162 "vxs.xs"
{
    if ( hv_exists(MUTABLE_HV(lobj), "alpha", 5 ) )
        XSRETURN_YES;
    else
        XSRETURN_NO;
}
#line 433 "vxs.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_version__vxs_qv); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_version__vxs_qv)
{
    dVAR; dXSARGS;
    dXSI32;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 174 "vxs.xs"
{
    SV *ver = ST(0);
    SV * rv;
    const char * classname = "";
    PERL_UNUSED_ARG(ix);
    if ( items == 2 && SvOK(ST(1)) ) {
        /* getting called as object or class method */
        ver = ST(1);
    }
#ifdef SvVOK
    if ( !SvVOK(ver) ) { /* not already a v-string */
#endif
        rv = sv_newmortal();
        sv_setsv(rv,ver); /* make a duplicate */
        UPG_VERSION(rv, TRUE);
#ifdef SvVOK
    }
    else
    {
        rv = sv_2mortal(NEW_VERSION(ver));
    }
#endif
    classname =
	sv_isobject(ST(0)) /* get the class if called as an object method */
	    ? HvNAME_get(SvSTASH(SvRV(ST(0))))
	    : (char *)SvPV_nolen(ST(0));

    if ( items == 2 && strcmp(classname,"version") ) {
        /* inherited new() */
#if PERL_VERSION == 5
        sv_bless(rv, gv_stashpv((char *)classname, GV_ADD));
#else
        sv_bless(rv, gv_stashpv(classname, GV_ADD));
#endif
    }
    PUSHs(rv);
}
#line 487 "vxs.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_version__vxs_is_qv); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_version__vxs_is_qv)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "lobj");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	version_vxs	lobj;

        if (ISA_CLASS_OBJ(ST(0), "version")) {
	    lobj = SvRV(ST(0));
        }
        else
            Perl_croak(aTHX_ "lobj is not of type version::vxs")
;
#line 216 "vxs.xs"
{
    if ( hv_exists(MUTABLE_HV(lobj), "qv", 2 ) )
        XSRETURN_YES;
    else
        XSRETURN_NO;
}
#line 518 "vxs.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_version__vxs__VERSION); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_version__vxs__VERSION)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "sv, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	sv = ST(0)
;
#line 227 "vxs.xs"
{
    HV *pkg;
    GV **gvp;
    GV *gv;
    SV *ret;
    const char *undef;

    if (SvROK(sv)) {
        sv = (SV*)SvRV(sv);
        if (!SvOBJECT(sv))
            Perl_croak(aTHX_ "Cannot find version of an unblessed reference");
        pkg = SvSTASH(sv);
    }
    else {
        pkg = gv_stashsv(sv, FALSE);
    }

    gvp = pkg ? (GV**)hv_fetchs(pkg,"VERSION",FALSE) : Null(GV**);

    if (gvp && isGV(gv = *gvp) && (sv = GvSV(gv)) && SvOK(sv)) {
        sv = sv_mortalcopy(sv);
	if ( ! ISA_CLASS_OBJ(sv, "version::vxs"))
	    UPG_VERSION(sv, FALSE);
        undef = NULL;
    }
    else {
        sv = ret = &PL_sv_undef;
        undef = "(undef)";
    }

    if (items > 1) {
        SV *req = ST(1);

        if (undef) {
             if (pkg) {
                const char * const name = HvNAME_get(pkg);
#if PERL_VERSION == 5
                Perl_croak(aTHX_ "%s version %s required--this is only version ",
                            name, SvPVx_nolen_const(req));
#else
                Perl_croak(aTHX_ "%s does not define $%s::VERSION--version check failed",
                            name, name);
#endif
             }
             else {
#if PERL_VERSION >= 8
                 Perl_croak(aTHX_ "%s defines neither package nor VERSION--version check failed",
                            SvPVx_nolen_const(ST(0)) );
#else
                 Perl_croak(aTHX_ "%s does not define $%s::VERSION--version check failed",
                            SvPVx_nolen_const(ST(0)),
                            SvPVx_nolen_const(ST(0)) );
#endif
             }
        }

        if ( ! ISA_CLASS_OBJ(req, "version")) {
            /* req may very well be R/O, so create a new object */
            req = sv_2mortal( NEW_VERSION(req) );
        }

        if ( VCMP( req, sv ) > 0 ) {
            if ( hv_exists(MUTABLE_HV(SvRV(req)), "qv", 2 ) ) {
                req = VNORMAL(req);
                sv  = VNORMAL(sv);
            }
            else {
                req = VSTRINGIFY(req);
                sv  = VSTRINGIFY(sv);
            }
            Perl_croak(aTHX_ "%s version %"SVf" required--"
                "this is only version %"SVf"", HvNAME_get(pkg),
                SVfARG(sv_2mortal(req)),
                SVfARG(sv_2mortal(sv)));
        }
    }
    ST(0) = ret;

    /* if the package's $VERSION is not undef, it is upgraded to be a version object */
    if (ISA_CLASS_OBJ(sv, "version")) {
	ST(0) = sv_2mortal(VSTRINGIFY(sv));
    } else {
	ST(0) = sv;
    }

    XSRETURN(1);
}
#line 624 "vxs.c"
	PUTBACK;
	return;
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_version__vxs); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_version__vxs)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    {
        CV * cv;

        cv = newXS("version::vxs::new", XS_version__vxs_new, file);
        XSANY.any_i32 = 0;
        cv = newXS("version::vxs::parse", XS_version__vxs_new, file);
        XSANY.any_i32 = 1;
        newXS("version::vxs::stringify", XS_version__vxs_stringify, file);
        newXS("version::vxs::numify", XS_version__vxs_numify, file);
        newXS("version::vxs::normal", XS_version__vxs_normal, file);
        newXS("version::vxs::VCMP", XS_version__vxs_VCMP, file);
        newXS("version::vxs::boolean", XS_version__vxs_boolean, file);
        newXS("version::vxs::noop", XS_version__vxs_noop, file);
        newXS("version::vxs::is_alpha", XS_version__vxs_is_alpha, file);
        cv = newXS("version::vxs::qv", XS_version__vxs_qv, file);
        XSANY.any_i32 = 0;
        cv = newXS("version::vxs::declare", XS_version__vxs_qv, file);
        XSANY.any_i32 = 1;
        newXS("version::vxs::is_qv", XS_version__vxs_is_qv, file);
        newXS("version::vxs::_VERSION", XS_version__vxs__VERSION, file);
    }

    /* Initialisation Section */

#line 20 "vxs.xs"
        /* register the overloading (type 'A') magic */
        PL_amagic_generation++;
        newXS("version::vxs::()", XS_version__vxs_noop, file);
        newXS("version::vxs::(\"\"", XS_version__vxs_stringify, file);
        newXS("version::vxs::(0+", XS_version__vxs_numify, file);
        newXS("version::vxs::(cmp", XS_version__vxs_VCMP, file);
        newXS("version::vxs::(<=>", XS_version__vxs_VCMP, file);
        newXS("version::vxs::(bool", XS_version__vxs_boolean, file);
        newXS("version::vxs::(+", XS_version__vxs_noop, file);
        newXS("version::vxs::(-", XS_version__vxs_noop, file);
        newXS("version::vxs::(*", XS_version__vxs_noop, file);
        newXS("version::vxs::(/", XS_version__vxs_noop, file);
        newXS("version::vxs::(+=", XS_version__vxs_noop, file);
        newXS("version::vxs::(-=", XS_version__vxs_noop, file);
        newXS("version::vxs::(*=", XS_version__vxs_noop, file);
        newXS("version::vxs::(/=", XS_version__vxs_noop, file);
        newXS("version::vxs::(abs", XS_version__vxs_noop, file);
        newXS("version::vxs::nomethod", XS_version__vxs_noop, file);

#line 692 "vxs.c"

    /* End of Initialisation Section */

#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

