#!/bin/sh
##############################################
diskname="hda "
status=`iostat -d -k 1 1 | grep "hda "`
times=` echo $status | awk '{print $4}'`
if [ ! -z $times ]
then 
	echo "OK -diskname=$diskname  info:$status |times=$times "
	exit 0
else
	echo "UNKNOWN"
	exit 3
fi
