#!/bin/sh
#-------------------------------------------------------
EsxiHostip=$1
warning="WARNING"
critical="CRITICAL"
ok="OK"




result=`cat /usr/local/nagios/libexec/ESXICheck/ESXICheckResults/ESXiCPUResults.info | grep $EsxiHostip`




echo "$result" |grep -q "$ok"  >null
if [ $? -eq 0 ]
then
    
    exitcode=0
fi




echo "$result" |grep -q "$warning"  >null
if [ $? -eq 0 ]
then
    exitcode=1
fi



echo "$result" |grep -q "$critical"  >null
if [ $? -eq 0 ]
then
    echo $result
    exitcode=2
fi

echo $result
exit $exitcode
