#! /usr/bin/perl

use strict;
use Cwd;
use File::Basename;
use File::Spec;

sub magic_number_matches {
  return 0 unless -e '_build/magicnum';
  my $FH;
  open $FH, '<','_build/magicnum' or return 0;
  my $filenum = <$FH>;
  close $FH;
  return $filenum == 481082;
}

my $progname;
my $orig_dir;
BEGIN {
  $^W = 1;  # Use warnings
  $progname = basename($0);
  $orig_dir = Cwd::cwd();
  my $base_dir = '/download/nagiospackages/nagios-plugins-2.1.2/perlmods/Module-Build-0.4007';
  if (!magic_number_matches()) {
    unless (chdir($base_dir)) {
      die ("Couldn't chdir($base_dir), aborting\n");
    }
    unless (magic_number_matches()) {
      die ("Configuration seems to be out of date, please re-run 'perl Build.PL' again.\n");
    }
  }
  unshift @INC,
    (
     't/lib',
     't/bundled',
     'lib',
     '/download/nagiospackages/nagios-plugins-2.1.2/perlmods/version-0.9903/blib/lib',
     '/download/nagiospackages/nagios-plugins-2.1.2/perlmods/version-0.9903/blib/arch',
     '/download/nagiospackages/nagios-plugins-2.1.2/perlmods/Module-Metadata-1.000014/blib/lib',
     '/download/nagiospackages/nagios-plugins-2.1.2/perlmods/Module-Metadata-1.000014/blib/arch',
     '/download/nagiospackages/nagios-plugins-2.1.2/perlmods/Module-Implementation-0.07/blib/lib',
     '/download/nagiospackages/nagios-plugins-2.1.2/perlmods/Module-Implementation-0.07/blib/arch',
     '/download/nagiospackages/nagios-plugins-2.1.2/perlmods/Perl-OSType-1.003/blib/lib',
     '/download/nagiospackages/nagios-plugins-2.1.2/perlmods/Perl-OSType-1.003/blib/arch',
     '/download/nagiospackages/nagios-plugins-2.1.2/perlmods/Test-Simple-0.98/blib/lib',
     '/download/nagiospackages/nagios-plugins-2.1.2/perlmods/Test-Simple-0.98/blib/arch'
    );
}

close(*DATA) unless eof(*DATA); # ensure no open handles to this script

use Module::Build;
Module::Build->VERSION(q{0});

# Some platforms have problems setting $^X in shebang contexts, fix it up here
$^X = Module::Build->find_perl_interpreter;

if (-e 'Build.PL' and not Module::Build->up_to_date('Build.PL', $progname)) {
   warn "Warning: Build.PL has been altered.  You may need to run 'perl Build.PL' again.\n";
}

# This should have just enough arguments to be able to bootstrap the rest.
my $build = Module::Build->resume (
  properties => {
    config_dir => '_build',
    orig_dir => $orig_dir,
  },
);

$build->dispatch;
