#!/bin/sh
##################################################################
#get average speed of last 5 s
speed=`sar 5 1 -n DEV |  grep "Average:         eth0" | awk '{print $5+$6}'`
timenow=`date +%T`
if [  -n $speed ]
then 
	echo " $timenow : the average speed of last 5 s is: $speed bps "
	exit 0
else 
	echo " $timenow may be  the script isnot executed "
	exit 3
fi
