#!/bin/sh
##################################################################
#init var
diskname=$1
#diskname=sda1
status=3

################################################################
#echo init finished
##################################################################
rt=`df -h |grep $diskname | awk '{print  $5 }'`
info=`df -h |grep $diskname`
rate=` echo $rt | awk -F"%" '{print $1}'`
#echo $rt
if [ $rate -le 50 ]
then
	echo "OK - The disk usage rate is  $rt .The detail info :$info "
	exit 0
elif ( [ $rate -gt 50  ] && [ $rate -le 80 ] )	
then 
	echo "WARNING - The disk usage rate is : $rt .The detail info :$info "
        exit 1
elif [ $rate -gt 80 ]
then 
	echo "CRITICAL - The disk usage rate is : $rt . The detail info :$info "
        exit 2
else
	echo "UNKNOWN - May be the script is not performed "
	exit 3
fi

